

namespace test_component_derived
{
    namespace Nested
    {
        unsealed runtimeclass HierarchyC : test_component_base.HierarchyB
        {
            HierarchyC();
            HierarchyC(String name);

            static HierarchyC CreateDerivedHierarchyD();
            static Object CreateDerivedHierarchyDAsObject();
            static Windows.Foundation.Collections.IVector<HierarchyC> CreateDerivedHierarchyDList();
            static Windows.Foundation.Collections.IVector<Object> CreateDerivedHierarchyDAsObjectList();

            void HierarchyC_Method();
        }

        unsealed runtimeclass HierarchyD : HierarchyC
        {
            HierarchyD();
            HierarchyD(String name);

            void HierarchyD_Method();
        }

    }
}
