
namespace TestComponent
{
    interface ITests
    {
        void Simple();

        Boolean Params_Bool(Boolean a, out Boolean b);
        UInt8 Params_UInt8(UInt8 a, out UInt8 b);
        UInt16 Params_UInt16(UInt16 a, out UInt16 b);
        UInt32 Params_UInt32(UInt32 a, out UInt32 b);
        UInt64 Params_UInt64(UInt64 a, out UInt64 b);
        Int16 Params_Int16(Int16 a, out Int16 b);
        Int32 Params_Int32(Int32 a, out Int32 b);
        Int64 Params_Int64(Int64 a, out Int64 b);
        Single Params_Single(Single a, out Single b);
        Double Params_Double(Double a, out Double b);
        Char Params_Char(Char a, out Char b);
        String Params_String(String a, out String b);

        Boolean[] ArrayParams_Bool(Boolean[] a, ref Boolean[] b, out Boolean[] c);
        UInt8[] ArrayParams_UInt8(UInt8[] a, ref UInt8[] b, out UInt8[] c);
        UInt16[] ArrayParams_UInt16(UInt16[] a, ref UInt16[] b, out UInt16[] c);
        UInt32[] ArrayParams_UInt32(UInt32[] a, ref UInt32[] b, out UInt32[] c);
        UInt64[] ArrayParams_UInt64(UInt64[] a, ref UInt64[] b, out UInt64[] c);
        Int16[] ArrayParams_Int16(Int16[] a, ref Int16[] b, out Int16[] c);
        Int32[] ArrayParams_Int32(Int32[] a, ref Int32[] b, out Int32[] c);
        Int64[] ArrayParams_Int64(Int64[] a, ref Int64[] b, out Int64[] c);
        Single[] ArrayParams_Single(Single[] a, ref Single[] b, out Single[] c);
        Double[] ArrayParams_Double(Double[] a, ref Double[] b, out Double[] c);
        Char[] ArrayParams_Char(Char[] a, ref Char[] b, out Char[] c);
        String[] ArrayParams_String(String[] a, ref String[] b, out String[] c);
}

    delegate void TestHandler(ITests tests);

    runtimeclass TestRunner
    {
        static void TestCallee(ITests callee);
        static UInt32 TestCaller(TestHandler caller);
        static void TestSelf();
    }
}
