
namespace TestComponent
{
    interface ITests
    {
        void T1_Simple();

        Boolean T2_Bool(Boolean a, out Boolean b);
        UInt8 T3_UInt8(UInt8 a, out UInt8 b);
        UInt16 T4_UInt16(UInt16 a, out UInt16 b);
        UInt32 T5_UInt32(UInt32 a, out UInt32 b);
        UInt64 T6_UInt64(UInt64 a, out UInt64 b);
        Int16 T7_Int16(Int16 a, out Int16 b);
        Int32 T8_Int32(Int32 a, out Int32 b);
        Int64 T9_Int64(Int64 a, out Int64 b);
        Single T10_Single(Single a, out Single b);
        Double T11_Double(Double a, out Double b);
        Char T12_Char(Char a, out Char b);
        String T13_String(String a, out String b);
}

    delegate void TestHandler(ITests tests);

    runtimeclass TestRunner
    {
        static void TestCallee(ITests callee);
        static UInt32 TestCaller(TestHandler caller);
        static void TestSelf();
    }
}
