// Modern IDL 3.0: https://docs.microsoft.com/en-us/uwp/midl-3/intro

// BenchmarkComponent exercises indivdual isolated scenarios we want to benchmark in a WinRT projection.

namespace BenchmarkComponent
{
    interface IIntProperties
    {
        Int32 IntProperty{ get; set; };
    }

    interface IBoolProperties
    {
        Boolean BoolProperty{ get; set; };
    }

    interface IDoubleProperties
    {
        Double DoubleProperty{ get; set; };
    }

    interface IEvents
    {
        event Windows.Foundation.EventHandler<Int32> IntPropertyChanged;
        event Windows.Foundation.EventHandler<Double> DoublePropertyChanged;
        void RaiseIntChanged();
        void RaiseDoubleChanged();
    }

    struct BlittableStruct
    {
        Int32 i32;
    };

    struct NonBlittable
    {
        Boolean A;
        String C;
    };

    delegate Int32 ProvideInt();

    // Class intended to help with benchmarking QueryInterface for the default and non default interfaces.
    [default_interface]
    runtimeclass ClassWithMultipleInterfaces :
        IIntProperties
        , IBoolProperties
        , IDoubleProperties
    {
        ClassWithMultipleInterfaces();

        Int32 DefaultIntProperty{ get; set; };
        Boolean DefaultBoolProperty{ get; set; };
        Double DefaultDoubleProperty{ get; set; };
        Object DefaultObjectProperty{ get; set; };
        String DefaultStringProperty{ get; set; };
        Object NewObject();

        void QueryBoolInterface(IIntProperties properties);
    }

    unsealed runtimeclass Composable : IBoolProperties
    {
        Composable();
    }

    [default_interface]
    runtimeclass WrappedClass
    {
        WrappedClass();

        Int32 DefaultIntProperty{ get; set; };
    }
    

    [default_interface]
    runtimeclass ClassWithMarshalingRoutines
    {
        ClassWithMarshalingRoutines();

        String DefaultStringProperty{ get; set; };
        IInspectable NewTypeErasedKeyValuePairObject{ get; set; };
        IInspectable NewTypeErasedNullableObject{ get; set; };
        IInspectable NewTypeErasedArrayObject{ get; set; };

        IInspectable ExistingTypeErasedKeyValuePairObject{ get; set; };
        IInspectable ExistingTypeErasedNullableObject{ get; set; };
        IInspectable ExistingTypeErasedArrayObject{ get; set; }; 

        WrappedClass NewWrappedClassObject{ get; set; };

        Windows.Foundation.Uri NewUri{ get; set; };
        Windows.Foundation.Uri ExistingUri{ get; set; };

        Windows.UI.Xaml.Interop.TypeName NewType{ get; set; };
        Windows.UI.Xaml.Interop.TypeName ExistingType{ get; set; };

        Int32 IntProperty;
        event Windows.Foundation.EventHandler<Int32> IntPropertyChanged;
        event Windows.Foundation.EventHandler<Double> DoublePropertyChanged;
        void RaiseIntChanged();
        void RaiseDoubleChanged();
        void CallForInt(ProvideInt provideInt);

        Windows.Foundation.Collections.IMap<String, WrappedClass> ExistingDictionary{ get; };
        Windows.Foundation.Collections.IVector<String> NewList();

        Windows.Foundation.IReference<Int32> NullableInt{ get; set; };
        Windows.Foundation.IReference<BlittableStruct> NullableBlittableStruct{ get; set; };
        Windows.Foundation.IReference<NonBlittable> NullableNonBlittableStruct{ get; set; };
        Windows.Foundation.IReference<Windows.Foundation.TimeSpan> NullableTimeSpan{ get; set; };
        Object BoxedDelegate{ get; set; };

        ProvideInt NewIntDelegate{ get; };
        ProvideInt ExistingIntDelegate{ get; };

        void GetWeakReference(Object obj);
        Object GetAndResolveWeakReference(Object obj);
    }

    [default_interface]
    [fastabi(1.0)]
    [version(1.0)]
    unsealed runtimeclass ClassWithFastAbi : NonDefaultFastAbiInterface
    {
        ClassWithFastAbi();
        Int32 DefaultIntProperty { get; };
    }

    [exclusiveto(ClassWithFastAbi)]
    [version(2.0)]
    interface NonDefaultFastAbiInterface
    {
        Int32 NonDefaultIntProperty{ get; };
    };

    [default_interface]
    [fastabi(1.0)]
    [version(1.0)]
    runtimeclass ClassWithFastAbiDerived : ClassWithFastAbi
    {
        ClassWithFastAbiDerived();
        Int32 DerivedDefaultIntProperty{ get; };
        [version(2.0)]
        {
            Int32 DerivedNonDefaultIntProperty{ get; };
        }
    }

    [default_interface]
    runtimeclass EventOperations
    {
        EventOperations(IEvents instance);

        void AddIntEvent();
        void AddDoubleEvent();
        void RemoveIntEvent();
        void RemoveDoubleEvent();
        void FireIntEvent();
        void FireDoubleEvent();
    }
}