name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout project
      uses: actions/checkout@v4

    - name: setup msbuild
      uses: microsoft/setup-msbuild@v2

    - name: setup nuget
      uses: NuGet/setup-nuget@v2
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}

    - name: setup cppwinrt
      run: nuget restore test.sln

    - name: build x86
      run: msbuild /m /p:Configuration=Release,Platform=x86 test.sln

    - name: build x64
      run: msbuild /m /p:Configuration=Release,Platform=x64 test.sln

    - name: build ARM64
      run: msbuild /m /p:Configuration=Release,Platform=ARM64 test.sln

    - name: nuget pack
      run: nuget.exe pack TestComponent/TestComponent.nuspec -OutputFileNamesWithoutVersion

    - name: nuget push
      run: nuget push PyWinRT.TestWinRT.nupkg -Source nuget.org
