name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout project
      uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

    - name: setup msbuild
      uses: microsoft/setup-msbuild@ede762b26a2de8d110bb5a3db4d7e0e080c0e917 # v1.3.3

    - name: setup nuget
      uses: NuGet/setup-nuget@255f46e14d51fbc603743e2aa2907954463fbeb9 # v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: setup cppwinrt
      run: nuget restore test.sln

    - name: build x86
      run: msbuild /m /p:Configuration=Release,Platform=x86 test.sln

    - name: build x64
      run: msbuild /m /p:Configuration=Release,Platform=x64 test.sln

    - name: nuget pack
      run: nuget.exe pack TestComponent/TestComponent.nuspec -OutputFileNamesWithoutVersion

    - name: nuget push
      run: nuget push KennyKerr.Windows.TestWinRT.nupkg ${{ secrets.NUGET_KEY }} -Source nuget.org
