name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout project
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: setup msbuild
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

    - name: setup nuget
      uses: NuGet/setup-nuget@b26b823c478ee115be5c9403e62c90b0bf943843 # v3.1.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: setup cppwinrt
      run: nuget restore test.sln

    - name: build x86
      run: msbuild /m /p:Configuration=Release,Platform=x86 test.sln

    - name: build x64
      run: msbuild /m /p:Configuration=Release,Platform=x64 test.sln

    - name: nuget pack
      run: nuget.exe pack TestComponent/TestComponent.nuspec -OutputFileNamesWithoutVersion

    - name: nuget push
      run: nuget push KennyKerr.Windows.TestWinRT.nupkg ${{ secrets.NUGET_KEY }} -Source nuget.org
